services:
  dev-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: intern
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskghar

volumes:
  postgres_data:

networks:
  taskghar:
